language: node_js
node_js:
  - "10"

cache: npm

branches:
  only: master

notifications:
  email: false

before_script:
  - npm install -g gulp-cli
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
script: gulp build-publish

